name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Backend
      - name: Install backend dependencies
        run: npm install
        working-directory: paynest-backend

      - name: Build backend
        run: npm run build
        working-directory: paynest-backend

      - name: Lint backend
        run: npm run lint || echo "Lint warnings"
        working-directory: paynest-backend

      # Frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Lint frontend
        run: npm run lint || echo "Lint warnings"
        working-directory: frontend
